version: '3.8'

volumes:
  db-volume:

services:
  app:
    build: ./php
    volumes:
      - ../src/:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password

  web:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ../src/:/var/www/html
    depends_on:
      - db
      - app

  db:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
    volumes:
      - db-volume:/var/lib/mysql

